POST http://localhost:3000/api/stars HTTP/1.1
Content-Type: application/json

{
    "nickname": "Wonder Woman",
    "realName": "Diana Prince",
    "description": "Beautiful as Aphrodite, wise as Athena, swifter than Hermes, and stronger than Hercules, Princess Diana of Themyscira fights for peace in Man's World.",
    "catchphrase": "I will fight for those who cannot fight for themselves."
}